// Code generated by raindrop build, DO NOT EDIT.
import { Ai, Annotation, App, KvCache, Logger, MRNObject, Queue, ServiceStub, SqlDatabase, Tracer,  } from '@liquidmetal-ai/raindrop-framework';

export interface Env {
  _raindrop: {
    app: App;
  };
  AI: Ai;
  annotation: Annotation<Omit<MRNObject, 'type' | 'applicationName' | 'versionId'>>;
  ANTHROPIC_API_KEY: string;
  BRAVE_SEARCH_API_KEY: string;
  ELEVENLABS_API_KEY: string;
  ELEVENLABS_JAMES_VOICE_ID: string;
  ELEVENLABS_SARAH_VOICE_ID: string;
  CIVIC_DB: SqlDatabase;
  logger: Logger;
  mem: KvCache;
  NEWS_QUEUE: Queue<import('../news-worker').Body>;
  PEXELS_API_KEY: string;
  TEST_SERVICE: ServiceStub<import('../test-service/index.js').default>;
  tracer: Tracer;
  VULTR_ACCESS_KEY: string;
  VULTR_CDN_URL: string;
  VULTR_SECRET_KEY: string;
  VULTR_STORAGE_ENDPOINT: string;
}
