import { NextResponse } from 'next/server';

/**
 * Test endpoint to display the latest daily brief for user_01K8NC5EJ3JBZKC9EQRQBQQVK4
 * This demonstrates the complete brief data structure for frontend display
 */
export async function GET() {
  try {
    // Mock data based on the actual brief generated
    const briefData = {
      briefId: 'brief-1762746194911',
      userId: 'user_01K8NC5EJ3JBZKC9EQRQBQQVK4',
      type: 'daily',
      generatedAt: new Date().toISOString(),
      duration: 300, // 5 minutes

      // Audio podcast
      audioUrl: 'https://sjc1.vultrobjects.com/civic-pulse-podcasts/podcasts/user_01K8NC5EJ3JBZKC9EQRQBQQVK4/daily/1762746185102.mp3',

      // Feature image for social sharing
      featureImageUrl: 'https://sjc1.vultrobjects.com/civic-pulse-podcasts/podcasts/user_01K8NC5EJ3JBZKC9EQRQBQQVK4/daily/1762746194246-feature.jpg',

      // Written digest (3,718 characters of markdown)
      writtenDigest: `# Daily Civic Brief - ${new Date().toLocaleDateString()}

## Bills Covered

### Affordable Healthcare Access Act of 2025
**Bill Number:** HR-100
**Summary:** Expands healthcare access for self-employed individuals and small businesses through subsidies and tax credits.
**Latest Action:** 2025-07-23
**Impact Score:** 85/100

### Education Modernization Act
**Bill Number:** HR-245
**Summary:** Updates curriculum standards and provides funding for technology integration in schools.
**Latest Action:** 2025-07-15
**Impact Score:** 78/100

## News & Analysis

### [HEALTHCARE] Democratic and Republican leaders dig in on health care fight as shutdown drags on
Over the weekend, Trump continued to blame Democrats for the shutdown, but in a Saturday post on Truth Social, he appeared to offer a proposal for a new health care system.

**Key Points:**
- "Over the weekend, Trump continued to blame Democrats for the shutdown, but in a Saturday post on Truth Social, he appeared to offer a proposal for a new health care system that would 'take from the BIG, BAD Insurance Companies, give it to the people, and terminate, per Dollar spent, the worst Healthcare anywhere in the World, ObamaCare.'"
- "In an exclusive interview with 'Meet the Press,' House Minority Leader Hakeem Jeffries called on Republicans to negotiate a deal after Senate Democrats offered a new funding proposal."

**Source:** https://www.nbcnews.com/politics/congress/jeffries-lankford-shutdown-aca-healthcare-aca-rcna242770

### [HEALTHCARE] What is Trump's proposal to pay Americans directly for health care costs?
President Donald Trump has floated a proposal to put the billions of dollars that back Affordable Care Act tax credits directly in the pockets of Americans instead.

**Key Points:**
- "President Donald Trump has floated a proposal to put the billions of dollars that back Affordable Care Act tax credits directly in the pockets of Americans instead, as lawmakers have so far failed to find a solution."

**Source:** https://www.cnn.com/2025/11/09/politics/trump-pay-americans-directly-healthcare

### [EDUCATION] School district approves new technology initiative
Local school board votes to approve $2M investment in classroom technology and teacher training programs.

**Key Points:**
- "The initiative will bring tablets and interactive whiteboards to every classroom by fall 2026"
- "Teachers will receive comprehensive training on integrating technology into existing curriculum"

**Source:** https://example.com/education-news

---
*Generated by HakiVo - Your AI Civic Engagement Assistant*`,

      // Bills covered (for quick reference)
      billsCovered: [
        {
          id: 'hr100-119',
          billNumber: 'HR-100',
          title: 'Affordable Healthcare Access Act of 2025',
          category: 'Health',
          impactScore: 85
        },
        {
          id: '119-hr-245',
          billNumber: 'HR-245',
          title: 'Education Modernization Act',
          category: 'Education',
          impactScore: 78
        }
      ],

      // News articles covered
      newsArticles: [
        {
          title: 'Democratic and Republican leaders dig in on health care fight as shutdown drags on',
          topic: 'healthcare',
          url: 'https://www.nbcnews.com/politics/congress/jeffries-lankford-shutdown-aca-healthcare-aca-rcna242770'
        },
        {
          title: 'What is Trump\'s proposal to pay Americans directly for health care costs?',
          topic: 'healthcare',
          url: 'https://www.cnn.com/2025/11/09/politics/trump-pay-americans-directly-healthcare'
        },
        {
          title: 'School district approves new technology initiative',
          topic: 'education',
          url: 'https://example.com/education-news'
        }
      ],

      // Policy areas covered
      policyAreas: ['healthcare', 'education']
    };

    return NextResponse.json({
      success: true,
      brief: briefData,
      message: 'Daily brief data ready for frontend display'
    });

  } catch (error: any) {
    console.error('Test brief display error:', error);
    return NextResponse.json(
      { error: 'Failed to fetch brief data', message: error.message },
      { status: 500 }
    );
  }
}
