// Code generated by raindrop build, DO NOT EDIT.
import { ActorNamespace, Ai, Annotation, App, Bucket, KvCache, Logger, MRNObject, Queue, ServiceStub, SmartBucket, SmartMemory, SmartSql, SqlDatabase, Tracer,  } from '@liquidmetal-ai/raindrop-framework';

export interface Env {
  _raindrop: {
    app: App;
  };
  ADMIN_API: ServiceStub<import('../admin-api/index.js').default>;
  AI: Ai;
  ANALYTICS: SmartSql;
  annotation: Annotation<Omit<MRNObject, 'type' | 'applicationName' | 'versionId'>>;
  ANTHROPIC_API_KEY: string;
  AUDIO_QUEUE: Queue<import('../audio-generator-worker').Body>;
  BILLS_SMARTBUCKET: SmartBucket;
  BRAVE_SEARCH_API_KEY: string;
  BRIEF_JOB_STORAGE: Bucket;
  BRIEF_QUEUE: Queue<import('../orchestrator-worker').Body>;
  DATA_QUEUE: Queue<import('../data-fetcher-worker').Body>;
  ELEVENLABS_API_KEY: string;
  ELEVENLABS_JAMES_VOICE_ID: string;
  ELEVENLABS_SARAH_VOICE_ID: string;
  HAKIVO_DB: SqlDatabase;
  logger: Logger;
  mem: KvCache;
  MEMORY_INIT: ServiceStub<import('../memory-init/index.js').default>;
  NOTIFICATION_STATE: KvCache;
  PEXELS_API_KEY: string;
  PODCAST_AUDIO: Bucket;
  PODCAST_GENERATION_QUEUE: Queue<import('../podcast-queue-handler').Body>;
  PODCAST_GENERATOR: ActorNamespace<import('../podcast-generator/index.js').PodcastGenerator>;
  PREFERENCES: ServiceStub<import('../preferences/index.js').default>;
  QUEUE_API: ServiceStub<import('../queue-api/index.js').default>;
  RECOMMENDATION_UPDATES: Queue<import('../user-behavior-tracker').Body>;
  SCRIPT_QUEUE: Queue<import('../script-generator-worker').Body>;
  TEST_SERVICE: ServiceStub<import('../test-service/index.js').default>;
  tracer: Tracer;
  TRACKING: ServiceStub<import('../tracking/index.js').default>;
  UPLOAD_QUEUE: Queue<import('../upload-worker').Body>;
  USER_MEMORY: SmartMemory;
  USER_NOTIFICATIONS: Queue<import('../notification-handler').Body>;
  VULTR_ACCESS_KEY: string;
  VULTR_CDN_URL: string;
  VULTR_SECRET_KEY: string;
  VULTR_STORAGE_ENDPOINT: string;
  WEB: ServiceStub<import('../web/index.js').default>;
}
