-- Migration: Add search-specific columns for hybrid search architecture
-- Date: 2025-10-28
-- Purpose: Add SmartBuckets integration and search optimization columns

-- Add SmartBuckets tracking
ALTER TABLE bills ADD COLUMN smartbucket_key TEXT;
-- Format: "bills/{congress}/{billType}{billNumber}.json"
-- Example: "bills/119/hr1.json"

ALTER TABLE bills ADD COLUMN synced_to_smartbucket_at DATETIME;
-- When the bill was last synced to SmartBuckets

-- Add searchable_text for fast SQL LIKE queries
ALTER TABLE bills ADD COLUMN searchable_text TEXT;
-- Combined field: title + summary + sponsor_name + issue_categories
-- Used for quick SQL searches before falling back to Algolia/SmartBuckets

-- Create index on searchable_text for performance
CREATE INDEX IF NOT EXISTS idx_bills_searchable_text
ON bills(searchable_text);

-- Add plain English summary (AI-generated for better readability)
ALTER TABLE bills ADD COLUMN plain_english_summary TEXT;
-- Human-readable summary generated by Claude

-- Add tracking count (how many users track this bill)
ALTER TABLE bills ADD COLUMN tracking_count INTEGER DEFAULT 0;
-- Used for custom ranking in Algolia

-- Create index for SmartBucket sync tracking
CREATE INDEX IF NOT EXISTS idx_bills_smartbucket_sync
ON bills(synced_to_smartbucket_at);

-- Create index for tracking count (trending bills)
CREATE INDEX IF NOT EXISTS idx_bills_tracking_count
ON bills(tracking_count DESC, latest_action_date DESC);
