// Code generated by raindrop build, DO NOT EDIT.
import { ActorNamespace, Ai, Annotation, App, Bucket, KvCache, Logger, MRNObject, Queue, ServiceStub, SmartBucket, SqlDatabase, Tracer,  } from '@liquidmetal-ai/raindrop-framework';

export interface Env {
  _raindrop: {
    app: App;
  };
  AI: Ai;
  annotation: Annotation<Omit<MRNObject, 'type' | 'applicationName' | 'versionId'>>;
  BILLS_SMARTBUCKET: SmartBucket;
  CIVIC_DB: SqlDatabase;
  logger: Logger;
  mem: KvCache;
  NOTIFICATION_STATE: KvCache;
  PODCAST_AUDIO: Bucket;
  PODCAST_GENERATOR: ActorNamespace<import('../podcast-generator/index.js').PodcastGenerator>;
  tracer: Tracer;
  USER_NOTIFICATIONS: Queue<import('../notification-handler').Body>;
  WEB: ServiceStub<import('../web/index.js').default>;
}
