name: Daily Bill Sync

# HYBRID SYNC STRATEGY:
# 1. This workflow discovers NEW bills (metadata only) - ~5 minutes
# 2. Full details fetched on-demand when users view bills (auto-sync)
# 3. Runs daily at 2 AM UTC (9 PM EST / 6 PM PST)
# 4. Can be triggered manually via "Run workflow" button
on:
  schedule:
    - cron: '0 2 * * *'  # 2 AM UTC daily
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync-bills:
    name: Sync Bills from Congress.gov
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Fast sync: ~5 min fetch + ~20 min pipeline

    steps:
      # Step 1: Get the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci --ignore-scripts

      # Step 4: Fetch new bills from Congress.gov (metadata only)
      - name: Fetch new bills from Congress.gov
        env:
          CONGRESS_API_KEY: ${{ secrets.CONGRESS_API_KEY }}
          RAINDROP_SERVICE_URL: ${{ secrets.RAINDROP_SERVICE_URL }}
        run: |
          echo "📥 Fetching new bills from Congress.gov..."
          echo "⚡ Metadata only - full details fetched on-demand when users view bills"
          echo "🎯 Limit: 100 bills (discovers new bills from last ~48 hours)"
          npm run fetch:bills -- --congress=119 --limit=100
          echo "✅ New bills discovered and indexed"

      # Step 5: Run the processing pipeline
      - name: Run post-fetch pipeline
        env:
          RAINDROP_SERVICE_URL: ${{ secrets.RAINDROP_SERVICE_URL }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_ADMIN_KEY: ${{ secrets.ALGOLIA_ADMIN_KEY }}
        run: |
          echo "⚙️  Running post-fetch pipeline..."
          echo "  1. AI policy area inference"
          echo "  2. SmartBuckets indexing"
          echo "  3. Algolia sync"
          echo "  4. Search tests"
          npx tsx scripts/post-fetch-pipeline.ts
          echo "✅ Pipeline complete"

      # Step 6: Save sync status (for admin dashboard)
      - name: Save sync status
        if: always()  # Run even if previous steps failed
        env:
          RAINDROP_SERVICE_URL: ${{ secrets.RAINDROP_SERVICE_URL }}
        run: |
          echo "💾 Saving sync status..."

          # Determine status
          if [ ${{ job.status }} == 'success' ]; then
            STATUS='success'
          else
            STATUS='failure'
          fi

          # Save to database via API
          npx tsx -e "
          (async () => {
            const response = await fetch('${RAINDROP_SERVICE_URL}/api/admin/query', {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({
                table: 'sync_history',
                query: \`
                  INSERT INTO sync_history (
                    sync_type,
                    status,
                    started_at,
                    completed_at,
                    run_id,
                    run_url
                  ) VALUES (?, ?, ?, ?, ?, ?)
                \`,
                values: [
                  'daily_bill_sync',
                  '${STATUS}',
                  new Date().toISOString(),
                  new Date().toISOString(),
                  '${GITHUB_RUN_ID}',
                  'https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}'
                ]
              })
            });

            console.log('✅ Sync status saved');
          })();
          "

      # Step 7: Notify on failure
      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Sync failed! Check logs at:"
          echo "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

# Permissions needed for this workflow
permissions:
  contents: read
